name: 03 - Runners de workflow

on: 
  push:
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
        - name: Mostrar SO
          run: |
            echo "Este trabajo se ejecuta en un runner de Ubuntu"
            echo "El SO del runner es: $RUNNER_OS"
  macos-echo:
    runs-on: macos-latest
    steps:
        - name: Mostrar SO
          run: |
            echo "Este trabajo se ejecuta en un runner de macOS"
            echo "El SO del runner es: $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
        - name: Mostrar SO
          run: |
            echo "Este trabajo se ejecuta en un runner de Windows"
            echo "El SO del runner es: ${{ runner.os }}"